schema_version: 1

context:
  version: "0.51.1"

package:
  name: pypika
  version: ${{ version }}

source:
  url: https://github.com/kayak/pypika/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e22f411afa4e0ab1f3d45e3f00d2f8ea94246af2cd8e1a79de18e9a4129d51c4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.5.0

tests:
  - python:
      imports:
        - pypika
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pytest -vvv pypika/tests
    requirements:
      run:
        - pytest
        - parameterized >=0.9.0
        - coverage >=7.0.0
    files:
      source:
        - pypika/tests/

about:
  summary: A SQL query builder API for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/kayak/pypika

extra:
  recipe-maintainers:
    - thewchan
    - mccarthyryanc
